defaults: &defaults
  app_name: infinitus
  host: http://localhost:3000

development:
  <<: *defaults
  redis:
    cache:
      uri: 'redis://localhost:6379/1'
      namespace: 'cache'
      expires_in: 5400 # 90.minutes in seconds
    jobs:
      uri: 'redis://localhost:6379/3'

test:
  <<: *defaults
  redis:
    cache:
      uri: 'redis://localhost:6379/4'
      namespace: 'cache'
      expires_in: 5400 # 90.minutes in seconds
    jobs:
      uri: 'redis://localhost:6379/6'

staging:
  <<: *defaults
  host: <%= ENV['HOSTNAME'] %>
  redis:
    cache:
      uri: <%= ENV['REDISCLOUD_URL'] %>
      namespace: 'cache'
      expires_in: 5400 # 90.minutes in seconds
    jobs:
      uri: <%= ENV['REDIS_URL'] %>

production:
  <<: *defaults
  host: <%= ENV['HOSTNAME'] %>
  redis:
    cache:
      uri: <%= ENV['REDISCLOUD_URL'] %>
      namespace: 'cache'
      expires_in: 5400 # 90.minutes in seconds
    jobs:
      uri: <%= ENV['REDIS_URL'] %>
