defaults: &defaults
  app_name: infinitus
  host: http://localhost:3000

development:
  <<: *defaults
  redis:
    cache:
      uri: 'redis://localhost:6379/1'
      namespace: 'cache'
      expires_in: 5400 # 90.minutes in seconds
    session:
      uri: 'redis://localhost:6379/2'
      key: '_infinitus_session'
      expires_in: 5400 # 90.minutes in seconds
    jobs:
      client:
        size: 2
        url: 'redis://localhost:6379/3'
        namespace: 'jobs'
      server:
        size: 18
        url: 'redis://localhost:6379/3'
        namespace: 'jobs'

test:
  <<: *defaults
  redis:
    cache:
      uri: 'redis://localhost:6379/4'
      namespace: 'cache'
      expires_in: 5400 # 90.minutes in seconds
    jobs:
      client:
        size: 1
        url: 'redis://localhost:6379/6'
        namespace: 'jobs'
      server:
        size: 2
        url: 'redis://localhost:6379/6'
        namespace: 'jobs'

staging:
  <<: *defaults
  host: <%= ENV['HOSTNAME'] %>
  redis:
    cache:
      uri: <%= ENV['REDISCLOUD_URL'] %>
      namespace: 'cache'
      expires_in: 5400 # 90.minutes in seconds
    rack_cache:
      metastore: <%= ENV['REDISCLOUD_URL'] %>/metastore
      entitystore: <%= ENV['REDISCLOUD_URL'] %>/entitystore
    session:
      uri: <%= ENV['REDISTOGO_URL'] %>
      key: '_infinitus_session'
      expires_in: 5400 # 90.minutes in seconds
    jobs:
      client:
        size: 2
        url: <%= ENV['REDIS_URL'] %>
        namespace: 'jobs'
      server:
        size: 18
        url: <%= ENV['REDIS_URL'] %>
        namespace: 'jobs'

production:
  <<: *defaults
  host: <%= ENV['HOSTNAME'] %>
  redis:
    cache:
      uri: <%= ENV['REDISCLOUD_URL'] %>
      namespace: 'cache'
      expires_in: 5400 # 90.minutes in seconds
    rack_cache:
      metastore: <%= ENV['REDISCLOUD_URL'] %>/metastore
      entitystore: <%= ENV['REDISCLOUD_URL'] %>/entitystore
    session:
      uri: <%= ENV['REDISTOGO_URL'] %>
      key: '_infinitus_session'
      expires_in: 5400 # 90.minutes in seconds
    jobs:
      client:
        size: 2
        url: <%= ENV['REDIS_URL'] %>
        namespace: 'jobs'
      server:
        size: 18
        url: <%= ENV['REDIS_URL'] %>
        namespace: 'jobs'
