# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df90f41bc0e00ff80e86f7aa70776cb0c4cd139e4a7d5424b25aeb04c7ce7df77b212be9308ae0577d0beb8c6b864a546464778b3757f3bda1eae07735e7109

test:
  secret_key_base: 74db76ec0eb2c6a4e27757bf6bdf5c075cefcc9623b7b56d673954e8aa401bc90b237fadea4b1c9144eece1fada50b08814e5f5dee53f83048929edb3a30a6ce

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
